### ISSUE TITLE
None of the acpi_call working in turn_off_gpu.sh

### ISSUE THREAD

**Issue by saint-shark** [dglt1/optimus-switch#16]
`Trying \_SB.PCI0.P0P1.VGA._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed 

Trying \_SB.PCI0.P0P2.VGA._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB_.PCI0.OVGA.ATPX: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB_.PCI0.OVGA.XTPX: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.P0P3.PEGP._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.P0P2.PEGP._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.P0P1.PEGP._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.MXR0.MXM0._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEG1.GFX0._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEG0.GFX0.DOFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEG1.GFX0.DOFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEG0.PEGP._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.XVR0.Z01I.DGOF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEGR.GFX0._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEG.VID._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEG0.VID._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.P0P2.DGPU._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.P0P4.DGPU.DOFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.IXVE.IGPU.DGOF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.RP00.VGA._PS3: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.RP00.VGA.P3MO: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.GFX0.DSM._T_0: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.LPC.EC.PUBS._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.P0P2.NVID._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.P0P2.VGA.PX02: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB_.PCI0.PEGP.DGFX._OFF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB_.PCI0.VGA.PX02: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.PEG0.PEGP.SGOF: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
Trying \_SB.PCI0.AGP.VGA.PX02: /usr/share/acpi_call/examples/turn_off_gpu.sh: line 39: warning: command substitution: ignored null byte in input
failed
`

I'm using the latest nvidia drivers 440xx

**Comment by dglt1** [comment]
Hi, im mobile right now replying via email so I’ll have to be quick. Make sure acpi_call is installed and loaded `sudo modprobe acpi_call` before running the script. Also make sure you have kernel headers installed that match your kernel or dkms wont build the acpi_call module.

**Comment by saint-shark** [comment]
Running `sudo modprobe acpi_call` doesn't give any errors and proper kernel headers are also installed. I'm using Manjaro with i3 and linux kernel 4.19

**Comment by dglt1** [comment]
> Running `sudo modprobe acpi_call` doesn't give any errors and proper kernel headers are also installed. I'm using Manjaro with i3 and linux kernel 4.19

then acpi_call is loading as it should. post output of these commands in a code box so it's formatted properly
```
inxi -Fxxxza --no-host
journalctl -k --no-hostname| grep -Ei "peg|peg1|peg0|dsm|pegp|dgpu|dgfx"
```

**Comment by saint-shark** [comment]
Sorry for the late reply.
The github code formater is not farmating it properly so I'm attaching a pastbin link of the output:
https://pastebin.com/ZLkNHW7M

**Comment by saint-shark** [comment]
Solved the issue. Output of "/usr/share/acpi_call/examples/turn_off_gpu.sh" never gives success with any ACPI call(as said to do in the tutorial) but using the "gpu_switch_check.sh" gave me the working ACPI call. Thanks for making this project @dglt1, really appreciate it.
