### ISSUE TITLE
GLX extension not found in Intel Mode

### ISSUE THREAD

**Issue by BorysChajdas** [dglt1/optimus-switch#2]
@dglt1 Thanks for this tool, it works great but I have a small problem.
Today I installed Minecraft game, It is working okay in Nvidia Mode (lower fps comparing to Windows but this is probably drivers problem) but in Intel Mode it is crashing at launch due to GLFW error:
**GLFW error 65542: GLX: GLX extension not found**

It's not a big deal because I can reboot system and use Nvidia Mode to play games. But maybe it can be fixed (installing GLX for Intel drivers or something... idk)?

EDIT: I tested other game, there is same problem.

Here is full crash log:
```
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 4/21/19, 4:57 PM
Description: Initializing game

java.lang.IllegalStateException: GLFW error 65542: GLX: GLX extension not found
	at cgd.b(SourceFile:218)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1649)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1827)
	at cgd.<init>(SourceFile:99)
	at cgc.a(SourceFile:79)
	at cft.am(SourceFile:439)
	at cft.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cgd.b(SourceFile:218)
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
	at org.lwjgl.system.JNI.invokePPPP(Native Method)
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1649)
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1827)
	at cgd.<init>(SourceFile:99)
	at cgc.a(SourceFile:79)
	at cft.am(SourceFile:439)

-- Initialization --
Details:
Stacktrace:
	at cft.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Linux (amd64) version 4.15.0-29deepin-generic
	Java Version: 10.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 304997360 bytes (290 MB) / 402653184 bytes (384 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2
	LWJGL: 3.1.6 build 14
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```
glxinfo:
```
name of display: :0
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Error: couldn't find RGB GLX visual or fbconfig
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".

Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
```

**Comment by dglt1** [comment]
this is a glx issue. there was an issue not too long ago with mesa throwing errors like the ones you posted and required allowing a downgrade of mesa so first try running a mirror sync and a full update with downgrade enabled.
`sudo pacman-mirrors -f8 && sudo pacman -Syyuu`

if prompted, answer yes to all. reboot after and test.

if thats not enough, try reinstalling mesa/glx related packages
`sudo pacman -S mesa freeglut glew glslang glu lib32-freeglut lib32-freeglut lib32-glu lib32-mesa libepoxy lib32-mesa-vdpau mesa-demos lib32-libva1 libva libva1`

after a reboot, GLX should work. test with `glxgears` and `glxinfo`. let me know how it goes.

**Comment by BorysChajdas** [comment]
@dglt1 Thanks, but unfortunately I can't try this because I'm using Deepin distro (Debian based) so I don't have `pacman` and that packages. Sorry for stupid question, but can I achieve this in another way using my distro?

**Comment by dglt1** [comment]
sorry for the late reply, i've been busy these past couple weeks. it's been a while since using a debian distro but the fix should be making sure mesa packages are installed. i would like to think these are available via deepin's package manager but im really not sure since i've never used it. 

optimus-switch was designed with manjaro/arch in mind but it's good to hear others are making use of it also.  i would just find the equivalent of the mesa packages for your distro, i believe manjaro installs them for you when installing drivers that use it but i guess deepin does not.  hope it all works out, do let me know.
