### ISSUE TITLE
How to delete optimus-switch 

### ISSUE THREAD

**Issue by wantedrbk** [dglt1/optimus-switch#21]
Can you help maybe you have script delete all configurations optimus switch , after deleting conf file , seems except this have something more , after deleting i ve nstalled  nvidia hybrid prime cant work with it  (some errors or black screen)

**Comment by dglt1** [comment]
theres an included uninstall script in /etc/switch/ . run that and it removes all of optimus-switch configurations. if your having trouble with render-offload prime (hybrid prime as you call it) then it's not due to anything related to optimus-switch.

**Comment by wantedrbk** [comment]
![switch](https://user-images.githubusercontent.com/55120646/78420942-78a50f80-7686-11ea-8dd8-7cc433e503e6.png)
