### ISSUE TITLE
No mhwd on Arch Linux 

### ISSUE THREAD

**Issue by fdiblen** [dglt1/optimus-switch#9]
The scripts work well on Arch Linux however, Arch doesn't use mhwd. The commands regarding mhwd should not be executed on Arch.

For example **/etc/X11/mhwd.d/** path does not exists.

**Comment by dglt1** [comment]
I originally created the scripts on manjaro, for manjaro but theres no reason they cant be used elsewhere. Even on manjaro the files in /etc/X11/mhwd.d/ are irrelevant and just used to symlink to xorg.conf.d , I’ve actually been meaning to remove the mhwd bits from the scripts anyway but I guess I forgot.  Thanks for bringing it up.

________________________________
